[tool.commitizen]
name = "cz_conventional_commits"
version = "0.3.0"
version_files = [
    "src/__init__.py",
    "pyproject.toml:version"
]
tag_format = "v$version"
bump_message = "bump: $current_version → $new_version [skip-ci]"

[tool.semantic_release]
version_variable = "setup.py:__version__"
