[tool.commitizen]
name = "cz_conventional_commits"
version = "0.2.1"
version_files = [
    "src/__init__.py",
    "pyproject.toml:version"
]
tag_format = "v$version"
bump_message = "bump: $current_version → $new_version [skip-ci]"
