---
name: Deploy to

on:
  workflow_dispatch:
    inputs:
      source:
        description: "Type of the source: 'tag or release'"
        required: true
        default: "tag"
      version:
        description: "Number in SemVer version format"
        required: true
        default: "latest"
      environment:
        description: "Environment goal to deploy"
        required: true
        default: "dev"

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          echo '**** ls '
          echo $(ls -rlta)
          echo '**** ls ../'
          echo $(ls -rlta ../)

      - name: Send greeting
        run: python hello.py ${{ inputs.environment }}

      - name: Show inputs
        run: |
          echo '\nSource: ${{ inputs.environment }}'
          echo '\nVersion: ${{ inputs.version }}'
          echo '\nEnvironment: ${{ inputs.environment }}'
