---
name: Deploy to dev

on:
  workflow_dispatch:
    inputs:
      name:
        # Friendly description to show in the UI instead of 'name'
        description: "Person to greet"
        required: true
        default: "DEV"

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: python hello.py ${{ inputs.name }}
